# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsvTpFH-abLNAGNJjNDbur2FHzWkYtDL
"""

import joblib
import pandas as pd

from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline

root = "/content/drive/MyDrive/projet_faux_monnayage/"
path_csv_file = "data/billets_df_cleaned.csv"
field_target = "is_genuine"

def set_target(column_target):
  return column_target

def set_csv_file(file):
  return file

def load_data(file_to_load):
  file = set_csv_file(file_to_load)
  df = pd.read_csv(file)
  return df

def save_data_csv(df, path):
  return df.to_csv(path, index=False)

def main():

  file = set_csv_file(root + path_csv_file)
  target = set_target(field_target)

  # Dataframe given
  df = load_data(file)

  model = joblib.load(root + "models/model.pkl")

  # Check if the model is in the pipeline or not, and extract from it
  if isinstance(model, Pipeline):
    final_estimator = model.steps[-1][1]
  else:
    final_estimator = model

  # Check if the model is unsupervised like KMeans or others
  if isinstance(final_estimator, KMeans):
    clusters = model.predict(df)
    df["clusters"] = clusters
    print(df)
    save_data_csv(df, root + "data/output.csv")

  # Or supervised and then need to split the target from the dataset
  else:
    # Check if the target is part of the columns
    if target in df.columns:
      X_df = df.drop(target, axis=1)
      y_true = df[target]
    else:
      X_df = df.copy()
      y_true = None

    predictions = model.predict(X_df)
    X_df[target] = y_true
    X_df["predictions"] = predictions

    # calculate the ratio prediction
    if y_true is not None:
      ratio_false_predictions = (y_true != predictions).sum() / len(X_df)
      print(f"{ratio_false_predictions*100:.2f}% of false predictions")

    print(X_df)
    save_data_csv(X_df, root + "data/output.csv")

if __name__ == "__main__":
  main()